title: Mobile Home
decluttering_templates: !include_dir_merge_named decluttering_templates/
kiosk_mode:
  hide_header: true
views:
  - title: Home
    type: sections
    max_columns: 1
    sections:
      - type: grid
        cards:
          - type: custom:button-card
            show_entity_picture: false
            show_icon: false
            show_label: true
            entity: |
              [[[
                return "person." + user.name.toLowerCase();
              ]]]
            name: '[[[return "Hello, " + user.name +"!"]]]'
            label: |
              [[[
                if (entity.state == "home") return "Welcome home.";
                else return "See you later.";
              ]]]
            tap_action:
              action: navigate
              navigation_path: settings
            state_not:
              - value: home
                styles:
                  entity_picture:
                    - filter: grayscale(100%)
            custom_fields:
              pic:
                card:
                  type: custom:button-card
                  entity: |
                    [[[
                      return entity.entity_id;
                    ]]]
                  show_name: false
                  show_entity_picture: true
                  state:
                    - value: not_home
                      styles:
                        entity_picture:
                          - filter: grayscale(100%)
                  styles:
                    card:
                      - background: none
                      - box-shadow: none
                      - border: none
                    entity_picture:
                      - width: 40px
                      - height: 40px
                      - border-radius: 10px
              one:
                card:
                  type: custom:button-card
                  entity: |
                    [[[
                      if (user.name == "Alex") return "person.pascale";
                      else return "person.alex";
                    ]]]
                  show_name: false
                  show_entity_picture: true
                  state_not:
                    - value: home
                      styles:
                        entity_picture:
                          - filter: grayscale(100%)
                          - opacity: 0.5
                  styles:
                    card:
                      - background: none
                      - box-shadow: none
                      - border: none
                    entity_picture:
                      - width: 40px
                      - height: 40px
                      - border-radius: 10px
            styles:
              card:
                - background: none
                - box-shadow: none
                - border: none
              grid:
                - grid-template-areas: '"pic n one" "pic l one"'
                - grid-template-rows: min-content min-content min-content
                - grid-template-columns: 50px 1fr 50px
                - grid-column-gap: 12px
              name:
                - justify-self: start
                - align-self: center
                - font-weight: 700
                - font-size: 15px
              label:
                - justify-self: start
                - align-self: start
                - font-size: 12px
                - font-weight: 500
                - color: var(--secondary-text-color)
              entity_picture:
                - width: 40px
                - height: 40px
                - border-radius: 12px
          - type: custom:button-card
            custom_fields:
              weather:
                card:
                  type: custom:decluttering-card
                  template: weather_card
              scenes:
                card:
                  type: custom:decluttering-card
                  template: scenes
              assist:
                card:
                  type: custom:button-card
                  icon: mdi:microphone-message
                  tap_action:
                    action: assist
                    pipeline_id: preferred
                    start_listening: true
                  hold_action:
                    action: assist
                    pipeline_id: preferred
                  styles:
                    card:
                      - justify-self: end
                      - background: none
                      - border: none
                    img_cell:
                      - background: var(--card-secondary-background-color)
                      - height: 60px
                      - width: 60px
                      - border-radius: 50%
                    icon:
                      - color: var(--secondary-text-color)
                      - width: 30px
            styles:
              grid:
                - grid-template-areas: |
                    "weather assist scenes"
                - grid-template-columns: 2fr 1fr 1fr
                - grid-template-rows: 60px
              card:
                - padding: 12px
                - background: var(--card-background-color)
                - border: none
          - type: vertical-stack
            cards:
              - type: horizontal-stack
                columns: 2
                cards:
                  - type: custom:decluttering-card
                    template: room_card
                    variables:
                      - temp_sensor_id: living_room
                      - name: Living Room
                      - icon: mdi:sofa
                      - template: living_room_chips
                      - tap_path: living-room 
                  - type: custom:decluttering-card
                    template: room_card
                    variables:
                      - temp_sensor_id: living_room
                      - name: Kitchen
                      - icon: mdi:fridge
                      - template: kitchen_chips
                      - tap_path: kitchen
              - type: horizontal-stack
                columns: 2
                cards:
                  - type: custom:decluttering-card
                    template: room_card
                    variables:
                      - temp_sensor_id: bedroom
                      - name: Bedroom
                      - icon: mdi:bed-king
                      - template: bedroom_chips
                      - tap_path: bedroom
                  - type: custom:decluttering-card
                    template: room_card
                    variables:
                      - name: Bathroom
                      - icon: mdi:bathtub
                      - template: bathroom_chips
                      - tap_path: bathroom
              - type: horizontal-stack
                columns: 2
                cards:
                  - type: custom:decluttering-card
                    template: room_card
                    variables:
                      - name: Office
                      - icon: mdi:desktop-classic
                      - template: office_chips
                      - tap_path: office
                  - type: custom:decluttering-card
                    template: room_card
                    variables:
                      - name: Balcony
                      - icon: mdi:balcony
                      - template: balcony_chips
                      - tap_path: balcony
  - type: sections
    max_columns: 1
    subview: true
    path: living-room
    sections:
      - type: custom:decluttering-card
        template: room_page
        variables:
          - name: Living Room
          - template: living_room_page
  - type: sections
    max_columns: 1
    subview: true
    path: kitchen
    sections:
      - type: custom:decluttering-card
        template: room_page
        variables:
          - name: Kitchen
          - template: kitchen_page
  - type: sections
    max_columns: 1
    subview: true
    path: bedroom
    sections:
      - type: custom:decluttering-card
        template: room_page
        variables:
          - name: Bedroom
          - template: bedroom_page
  - type: sections
    max_columns: 1
    subview: true
    path: bathroom
    sections:
      - type: custom:decluttering-card
        template: room_page
        variables:
          - name: Bathroom
          - template: bathroom_page
  - type: sections
    max_columns: 1
    subview: true
    path: office
    sections:
      - type: custom:decluttering-card
        template: room_page
        variables:
          - name: Office
          - template: office_page
  - type: sections
    max_columns: 1
    subview: true
    path: balcony
    sections:
      - type: custom:decluttering-card
        template: room_page
        variables:
          - name: Balcony
          - template: balcony_page
