title: Mobile Home
decluttering_templates: !include decluttering_templates.yaml
kiosk_mode:
  hide_header: true
views:
  - title: Home
    type: sections
    max_columns: 1
    sections:
      - type: grid
        cards:
          - type: custom:button-card
            show_entity_picture: false
            show_icon: false
            show_label: true
            entity: |
              [[[
                return "person." + user.name.toLowerCase();
              ]]]
            name: '[[[return "Hello, " + user.name +"!"]]]'
            label: |
              [[[
                if (entity.state == "home") return "Welcome home.";
                else return "See you later.";
              ]]]
            tap_action:
              action: navigate
              navigation_path: settings
            state_not:
              - value: home
                styles:
                  entity_picture:
                    - filter: grayscale(100%)
            styles:
              card:
                - background: none
                - box-shadow: none
                - border: none
              grid:
                - grid-template-areas: '"pic n one" "pic l one"'
                - grid-template-rows: min-content min-content min-content
                - grid-template-columns: 50px 1fr 50px
                - grid-column-gap: 15px
              name:
                - justify-self: start
                - align-self: center
                - font-weight: 700
                - font-size: 15px
              label:
                - justify-self: start
                - align-self: start
                - font-size: 12px
                - font-weight: 500
                - color: var(--contrast14)
              entity_picture:
                - width: 40px
                - height: 40px
                - border-radius: 12px
            custom_fields:
              pic:
                card:
                  type: custom:button-card
                  entity: |
                    [[[
                      return entity.entity_id;
                    ]]]
                  show_name: false
                  show_entity_picture: true
                  state:
                    - value: not_home
                      styles:
                        entity_picture:
                          - filter: grayscale(100%)
                  styles:
                    card:
                      - background: none
                      - box-shadow: none
                      - border: none
                    entity_picture:
                      - width: 40px
                      - height: 40px
                      - border-radius: 10px
              one:
                card:
                  type: custom:button-card
                  entity: |
                    [[[
                      if (user.name == "Alex") return "person.pascale";
                      else return "person.alex";
                    ]]]
                  show_name: false
                  show_entity_picture: true
                  state_not:
                    - value: home
                      styles:
                        entity_picture:
                          - filter: grayscale(100%)
                          - opacity: 0.5
                  styles:
                    card:
                      - background: none
                      - box-shadow: none
                      - border: none
                    entity_picture:
                      - width: 40px
                      - height: 40px
                      - border-radius: 10px
                    img_cell:
                      - background-color: var(--contrast1)
                      - width: 40px
                      - height: 40px
                      - border-radius: 10px
          - type: custom:button-card
            custom_fields:
              weather:
                card:
                  type: custom:button-card
                  show_state: true
                  entity: weather.forecast_home
                  icon: >
                    [[[
                      const state = states['weather.forecast_home'].state;
                      switch(state) {
                        case 'sunny':
                          return 'mdi:weather-sunny';
                        case 'partlycloudy':
                          return 'mdi:weather-partly-cloudy';
                        case 'cloudy':
                          return 'mdi:weather-cloudy';
                        case 'rainy':
                          return 'mdi:weather-rainy';
                        case 'snowy':
                          return 'mdi:weather-snowy';
                        case 'pouring':
                          return 'mdi:weather-pouring';
                        case 'lightning':
                          return 'mdi:weather-lightning';
                        case 'clear-night':
                          return 'mdi:weather-night';
                        default:
                          return 'mdi:thermometer';
                      }
                    ]]]
                  name: "[[[ return states['weather.forecast_home'].attributes.temperature + ' ' + states['weather.forecast_home'].attributes.temperature_unit ]]]"
                  state_display: |
                    [[[
                      return `${states['weather.forecast_home'].attributes.wind_speed} ${states['weather.forecast_home'].attributes.wind_speed_unit}`
                    ]]]
                  tap_action:
                    action: more-info
                  styles:
                    grid:
                      - grid-template-areas: |
                          "i n"
                          "i s"
                      - grid-template-columns: 60px auto
                      - grid-template-rows: auto auto
                    card:
                      - background: none
                      - border: none
                    name:
                      - justify-self: start
                      - font-size: 16px
                      - font-weight: 700
                      - margin-left: 10px
                    state:
                      - justify-self: start
                      - font-size: 14px
                      - color: var(--secondary-text-color)
                      - margin-left: 10px
                    img_cell:
                      - background: var(--card-background-color)
                      - height: 60px
                      - border-radius: 50%
                    icon:
                      - color: var(--secondary-text-color)
                      - width: 30px
              scenes:
                card:
                  type: custom:button-card
                  name: Scenes
            styles:
              grid:
                - grid-template-areas: |
                    "weather scenes"
                - grid-template-columns: 1fr 1fr
                - grid-template-rows: auto
              card:
                - padding: 12px
                - background: var(--secondary-background-color)
                - border: none
                - box-shadow: 0px 1px 8px black
          - type: vertical-stack
            cards:
              - type: horizontal-stack
                columns: 2
                cards:
                  - type: custom:decluttering-card
                    template: room_card
                    variables:
                      - name: Living Room
                      - icon: mdi:sofa
                      - template: living_room_chips
                  - type: custom:decluttering-card
                    template: room_card
                    variables:
                      - name: Kitchen
                      - icon: mdi:fridge
                      - template: kitchen_chips
              - type: horizontal-stack
                columns: 2
                cards:
                  - type: custom:decluttering-card
                    template: room_card
                    variables:
                      - name: Bedroom
                      - icon: mdi:bed-king
                      - template: bedroom_chips
                  - type: custom:decluttering-card
                    template: room_card
                    variables:
                      - name: Bathroom
                      - icon: mdi:bathtub
                      - template: bathroom_chips
              - type: horizontal-stack
                columns: 2
                cards:
                  - type: custom:decluttering-card
                    template: room_card
                    variables:
                      - name: Office
                      - icon: mdi:desktop-classic
                      - template: office_chips
                  - type: grid
                    cards: []
