views:
  - title: Home
    badges: []
    sections:
      - type: grid
        cards:
          - type: heading
            heading: Lighting
            heading_style: title
            icon: mdi:lightbulb
          - type: heading
            icon: mdi:sofa
            heading: Living Room
            heading_style: subtitle
          - type: custom:bubble-card
            card_type: button
            button_type: slider
            entity: light.couch_lamp
            use_accent_color: false
            scrolling_effect: true
            show_last_changed: false
            show_state: false
            show_attribute: true
            attribute: brightness
            slider_live_update: false
            icon: mdi:floor-lamp
            sub_button:
              - entity: light.couch_lamp
                icon: mdi:palette
                name: Color
            hold_action:
              action: more-info
            double_tap_action:
              action: more-info
            tap_action:
              action: toggle
          - type: custom:bubble-card
            card_type: button
            button_type: slider
            entity: light.globe_light
            use_accent_color: false
            scrolling_effect: true
            show_last_changed: false
            show_state: false
            show_attribute: true
            attribute: brightness
            slider_live_update: false
            icon: mdi:circle
            sub_button:
              - entity: light.globe_light
                icon: mdi:palette
                name: Color
            tap_action:
              action: toggle
            double_tap_action:
              action: more-info
            hold_action:
              action: more-info
          - type: heading
            icon: mdi:fridge
            heading: Kitchen
            heading_style: subtitle
          - type: custom:bubble-card
            card_type: button
            button_type: slider
            use_accent_color: false
            scrolling_effect: true
            show_last_changed: false
            show_state: false
            show_attribute: true
            attribute: brightness
            slider_live_update: false
            icon: mdi:ceiling-light
            sub_button:
              - entity: light.globe_light
                icon: mdi:palette
                name: Color
            entity: light.kitchen_lights
            tap_action:
              action: toggle
            double_tap_action:
              action: more-info
            hold_action:
              action: more-info
      - type: grid
        cards:
          - type: heading
            icon: mdi:speaker-multiple
            heading: Speakers
            heading_style: title
          - type: heading
            icon: mdi:bathtub
            heading: Bathroom
            heading_style: subtitle
          - type: custom:bubble-card
            card_type: media-player
            entity: media_player.bathroom_speaker
          - type: heading
            icon: mdi:bed
            heading: Bedroom
            heading_style: subtitle
          - type: custom:bubble-card
            card_type: media-player
            entity: media_player.bedroom_display
          - type: heading
            icon: mdi:fridge
            heading: Kitchen
            heading_style: subtitle
          - type: custom:bubble-card
            card_type: media-player
            entity: media_player.kitchen_speaker
          - type: heading
            icon: mdi:sofa
            heading: Living Room
            heading_style: subtitle
          - type: custom:bubble-card
            card_type: media-player
            entity: media_player.tv_soundbar
      - type: grid
        cards:
          - type: heading
            icon: mdi:plex
            heading: Plex
            heading_style: title
            badges:
              - type: entity
                show_state: true
                show_icon: true
                entity: sensor.alex
                state_content: state
                icon: mdi:cast-connected
                color: primary
                visibility:
                  - condition: state
                    entity: media_player.plex_plex_for_android_tv_shield_android_tv
                    state_not: 'off'
          - type: entities
            entities:
              - entity: sensor.alex_library_movies
                name: Movies
                tap_action:
                  action: url
                  url_path: https://radarr.alex-plex.xyz
              - entity: sensor.alex_library_tv_shows
                name: TV Shows
                tap_action:
                  action: url
                  url_path: https://sonarr.alex-plex.xyz
              - entity: sensor.overseerr_pending_requests
                name: Pending Requests
                tap_action:
                  action: url
                  url_path: https://alex-plex.xyz
            footer:
              type: buttons
              entities:
                - entity: script.open_plex
                  icon: mdi:play
                  name: Living Room TV
            show_header_toggle: false
            state_color: false
          - type: media-control
            entity: media_player.plex_plex_for_android_tv_shield_android_tv
            grid_options:
              columns: 12
              rows: 3
            visibility:
              - condition: state
                entity: media_player.plex_plex_for_android_tv_shield_android_tv
                state_not: 'off'
              - condition: state
                entity: media_player.plex_plex_for_android_tv_shield_android_tv
                state_not: unavailable
              - condition: state
                entity: media_player.plex_plex_for_android_tv_shield_android_tv
                state_not: idle
              - condition: state
                entity: media_player.plex_plex_for_android_tv_shield_android_tv
                state_not: unknown
        column_span: 1
      - type: grid
        cards:
          - type: heading
            icon: mdi:weather-cloudy
            heading_style: title
            heading: Weather
          - show_current: true
            show_forecast: true
            type: weather-forecast
            entity: weather.forecast_home
            forecast_type: daily
            name: Toronto, ON
          - type: custom:hourly-weather
            entity: weather.forecast_home
            num_segments: '12'
            offset: '0'
            label_spacing: '2'
            icons: true
            show_wind: 'false'
            show_date: 'false'
            show_precipitation_amounts: true
            show_precipitation_probability: true
            name: Next 12 Hours
          - type: custom:horizon-card
    type: sections
    max_columns: 4
    icon: mdi:home
    cards: []
  - type: sections
    path: ''
    max_columns: 4
    icon: mdi:lightbulb-on
    sections:
      - type: grid
        cards:
          - type: heading
            icon: mdi:sofa
            heading: Living Room
          - type: custom:bubble-card
            card_type: button
            button_type: slider
            entity: light.couch_lamp
            use_accent_color: false
            scrolling_effect: true
            show_last_changed: false
            show_state: false
            show_attribute: true
            attribute: brightness
            slider_live_update: false
            icon: mdi:floor-lamp
            sub_button:
              - entity: light.couch_lamp
                icon: mdi:palette
                name: Color
          - type: custom:bubble-card
            card_type: button
            button_type: slider
            entity: light.globe_light
            use_accent_color: false
            scrolling_effect: true
            show_last_changed: false
            show_state: false
            show_attribute: true
            attribute: brightness
            slider_live_update: false
            icon: mdi:circle
            sub_button:
              - entity: light.globe_light
                icon: mdi:palette
                name: Color
  - type: sections
    max_columns: 4
    icon: mdi:speaker-multiple
    path: ''
    sections:
      - type: grid
        cards:
          - type: heading
            icon: mdi:speaker-multiple
            heading: Speakers
            heading_style: title
          - type: heading
            icon: mdi:bathtub
            heading: Bathroom
            heading_style: subtitle
          - type: custom:bubble-card
            card_type: media-player
            entity: media_player.bathroom_speaker
          - type: heading
            icon: mdi:bed
            heading: Bedroom
            heading_style: subtitle
          - type: custom:bubble-card
            card_type: media-player
            entity: media_player.bedroom_display
          - type: heading
            icon: mdi:fridge
            heading: Kitchen
            heading_style: subtitle
          - type: custom:bubble-card
            card_type: media-player
            entity: media_player.kitchen_speaker
          - type: heading
            icon: mdi:sofa
            heading: Living Room
            heading_style: subtitle
          - type: custom:bubble-card
            card_type: media-player
            entity: media_player.tv_soundbar
  - type: sections
    icon: mdi:movie-open
    path: ''
    sections:
      - type: grid
        cards:
          - type: heading
            icon: mdi:plex
            heading: Plex
            heading_style: title
            badges:
              - type: entity
                show_state: true
                show_icon: true
                entity: sensor.alex
                state_content: state
                icon: mdi:cast-connected
                color: primary
                visibility:
                  - condition: state
                    entity: media_player.plex_plex_for_android_tv_shield_android_tv
                    state_not: 'off'
        column_span: 1
      - type: grid
        cards:
          - type: media-control
            entity: media_player.plex_plex_for_android_tv_shield_android_tv
            grid_options:
              columns: 12
              rows: 3
            visibility:
              - condition: state
                entity: media_player.plex_plex_for_android_tv_shield_android_tv
                state_not: 'off'
              - condition: state
                entity: media_player.plex_plex_for_android_tv_shield_android_tv
                state_not: unavailable
              - condition: state
                entity: media_player.plex_plex_for_android_tv_shield_android_tv
                state_not: idle
              - condition: state
                entity: media_player.plex_plex_for_android_tv_shield_android_tv
                state_not: unknown
      - type: grid
        cards:
          - type: heading
            heading: New section
          - type: entities
            entities:
              - entity: sensor.alex_library_movies
                name: Movies
                tap_action:
                  action: url
                  url_path: https://radarr.alex-plex.xyz
              - entity: sensor.alex_library_tv_shows
                name: TV Shows
                tap_action:
                  action: url
                  url_path: https://sonarr.alex-plex.xyz
              - entity: sensor.overseerr_pending_requests
                name: Pending Requests
                tap_action:
                  action: url
                  url_path: https://alex-plex.xyz
            footer:
              type: buttons
              entities:
                - entity: script.open_plex
                  icon: mdi:play
                  name: Living Room TV
            show_header_toggle: false
            state_color: false
      - type: grid
        cards:
          - type: heading
            heading: New section
    max_columns: 2
    cards: []
