- id: '1741918422543'
  alias: Play TV Show on Plex
  description: ''
  triggers:
  - trigger: conversation
    command:
    - Play the show {show} on Plex
  conditions: []
  actions:
  - type: turn_on
    device_id: 666a131febb9dd313ce248e9204154d0
    entity_id: 07288ef4874f5c43a52aa81853a42fb8
    domain: remote
    alias: Turn on The Box
  - wait_for_trigger:
    - trigger: state
      entity_id:
      - media_player.shield
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 5
    timeout:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - if:
    - condition: state
      entity_id: media_player.plex_shield
      state: unavailable
    then:
    - alias: Open Plex
      action: media_player.play_media
      data:
        media_content_id: com.plexapp.android
        media_content_type: app
      target:
        entity_id:
        - media_player.shield
    - wait_for_trigger:
      - trigger: state
        entity_id:
        - media_player.plex_shield
        from: unavailable
      timeout:
        hours: 0
        minutes: 0
        seconds: 5
        milliseconds: 0
    - action: button.press
      metadata: {}
      data: {}
      target:
        entity_id: button.alex_scan_clients
  - action: media_player.play_media
    data:
      media_content_type: EPISODE
      media_content_id: '{ "library_name": "TV Shows", "show_name": "{{ trigger.slots.show
        }}", "episode.unwatched": true, "episode.inProgress": [true, false], "resume":
        1, "sort": "year", "maxresults": 1 }'
    target:
      entity_id: media_player.plex_shield
  mode: single
- id: '1741926517429'
  alias: Play Movie on Plex
  description: ''
  triggers:
  - trigger: conversation
    command:
    - Play the movie {show} on Plex
  conditions: []
  actions:
  - type: turn_on
    device_id: 666a131febb9dd313ce248e9204154d0
    entity_id: 07288ef4874f5c43a52aa81853a42fb8
    domain: remote
    alias: Turn on The Box
  - wait_for_trigger:
    - trigger: state
      entity_id:
      - media_player.shield
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 5
    timeout:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - if:
    - condition: state
      entity_id: media_player.plex_shield
      state: unavailable
    then:
    - alias: Open Plex
      action: media_player.play_media
      data:
        media_content_id: com.plexapp.android
        media_content_type: app
      target:
        entity_id:
        - media_player.shield
    - wait_for_trigger:
      - trigger: state
        entity_id:
        - media_player.plex_shield
        from: unavailable
      timeout:
        hours: 0
        minutes: 0
        seconds: 5
        milliseconds: 0
    - action: button.press
      metadata: {}
      data: {}
      target:
        entity_id: button.alex_scan_clients
  - action: media_player.play_media
    data:
      media_content_type: movie
      media_content_id: 'plex://{ "library_name": "Movies", "title": "{{ trigger.slots.show
        }}"}'
    target:
      entity_id: media_player.plex_shield
  mode: single
- id: '1741926711468'
  alias: Play Current Show on Plex
  description: ''
  triggers: []
  conditions: []
  actions:
  - action: script.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: script.open_plex
  - action: media_player.play_media
    data:
      media_content_type: EPISODE
      media_content_id: '{ "library_name": "TV Shows", "episode.unwatched": true,
        "episode.inProgress": [true, false], "resume": 1, "sort": ["lastViewedAt:desc",
        "year"], "maxresults": 1 }'
    target:
      entity_id: media_player.plex_shield
  mode: single
- id: '1742764975788'
  alias: Bedroom Humidifier On
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - sensor.bedroom_climate_sensor_humidity
    below: 35
  conditions: []
  actions:
  - action: humidifier.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: humidifier.bedroom_humidifier
  mode: single
- id: '1743083579481'
  alias: Bedroom Humidifier Off
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - sensor.bedroom_climate_sensor_humidity
    for:
      hours: 0
      minutes: 20
      seconds: 0
    above: 45
  conditions: []
  actions:
  - action: humidifier.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: humidifier.bedroom_humidifier
  mode: single
- id: '1745644359091'
  alias: Leafs/Jays Score
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - sensor.toronto_maple_leafs
    attribute: team_score
  - trigger: state
    entity_id:
    - sensor.toronto_blue_jays
    attribute: team_score
  conditions:
  - condition: template
    value_template: '{{ trigger.from_state.attributes.team_score|int < trigger.to_state.attributes.team_score|int
      }}'
    enabled: true
  actions:
  - delay:
      hours: 0
      minutes: 0
      seconds: 20
      milliseconds: 0
    enabled: false
  - action: script.goal_light
    metadata: {}
    data: {}
    enabled: false
  - action: script.goal_light_leds
    metadata: {}
    data: {}
  mode: single
- id: '1753148845505'
  alias: Bird Spotted
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.bird_cam_cell_motion_detection
    from: 'off'
    to: 'on'
  conditions: []
  actions:
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - action: camera.snapshot
    target:
      entity_id: camera.bird_cam_hd_stream
    data:
      filename: /config/www/images/birdfeeder/bird.jpg
  - action: llmvision.image_analyzer
    metadata: {}
    data:
      include_filename: false
      target_width: 1280
      max_tokens: 100
      generate_title: false
      expose_images: false
      provider: 01K0NKGF7HGJ4EXN92T6MVNW0C
      message: 'You will identify images of bird(s) and give their species and sometimes
        gender based on the image. Respond, without quotes, with the following and
        ONLY the following. Sub in values to the {} denoted fields.  Articles and
        sentence grammar should remain correct, but otherwise keep the sentence the
        same:


        "A {gender} {species} is eating on the balcony!"


        If gender is unknown, omit the gender entirely. If species is unknown, just
        say "A bird is eating on the balcony!"


        If the image is not of a bird, simply respond (without quotes) "not_bird"'
      image_file: /config/www/images/birdfeeder/bird.jpg
      model: gemini-2.0-flash
    response_variable: response
  - if:
    - condition: template
      value_template: '{{ response.response_text != "not_bird" }}'
    then:
    - action: notify.mobile_app_alexs_iphone
      data:
        message: '{{response.response_text}}'
        title: Balcony Camera
        data:
          image: https://home.casamoreira.xyz/local/images/birdfeeder/bird.jpg
    - action: shell_command.save_bird_image
      data: {}
  mode: single
