- id: '1741918422543'
  alias: Play TV Show on Plex
  description: ''
  triggers:
  - trigger: conversation
    command:
    - Play the show {show} on Plex
  conditions: []
  actions:
  - type: turn_on
    device_id: 666a131febb9dd313ce248e9204154d0
    entity_id: 07288ef4874f5c43a52aa81853a42fb8
    domain: remote
    alias: Turn on The Box
  - wait_for_trigger:
    - trigger: state
      entity_id:
      - media_player.shield
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 5
    timeout:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - if:
    - condition: state
      entity_id: media_player.plex_shield
      state: unavailable
    then:
    - alias: Open Plex
      action: media_player.play_media
      data:
        media_content_id: com.plexapp.android
        media_content_type: app
      target:
        entity_id:
        - media_player.shield
    - wait_for_trigger:
      - trigger: state
        entity_id:
        - media_player.plex_shield
        from: unavailable
      timeout:
        hours: 0
        minutes: 0
        seconds: 5
        milliseconds: 0
    - action: button.press
      metadata: {}
      data: {}
      target:
        entity_id: button.alex_scan_clients
  - action: media_player.play_media
    data:
      media_content_type: EPISODE
      media_content_id: '{ "library_name": "TV Shows", "show_name": "{{ trigger.slots.show
        }}", "episode.unwatched": true, "episode.inProgress": [true, false], "resume":
        1, "sort": "year", "maxresults": 1 }'
    target:
      entity_id: media_player.plex_shield
  mode: single
- id: '1741926517429'
  alias: Play Movie on Plex
  description: ''
  triggers:
  - trigger: conversation
    command:
    - Play the movie {show} on Plex
  conditions: []
  actions:
  - type: turn_on
    device_id: 666a131febb9dd313ce248e9204154d0
    entity_id: 07288ef4874f5c43a52aa81853a42fb8
    domain: remote
    alias: Turn on The Box
  - wait_for_trigger:
    - trigger: state
      entity_id:
      - media_player.shield
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 5
    timeout:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - if:
    - condition: state
      entity_id: media_player.plex_shield
      state: unavailable
    then:
    - alias: Open Plex
      action: media_player.play_media
      data:
        media_content_id: com.plexapp.android
        media_content_type: app
      target:
        entity_id:
        - media_player.shield
    - wait_for_trigger:
      - trigger: state
        entity_id:
        - media_player.plex_shield
        from: unavailable
      timeout:
        hours: 0
        minutes: 0
        seconds: 5
        milliseconds: 0
    - action: button.press
      metadata: {}
      data: {}
      target:
        entity_id: button.alex_scan_clients
  - action: media_player.play_media
    data:
      media_content_type: movie
      media_content_id: 'plex://{ "library_name": "Movies", "title": "{{ trigger.slots.show
        }}"}'
    target:
      entity_id: media_player.plex_shield
  mode: single
- id: '1741926711468'
  alias: Play Current Show on Plex
  description: ''
  triggers: []
  conditions: []
  actions:
  - action: script.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: script.open_plex
  - action: media_player.play_media
    data:
      media_content_type: EPISODE
      media_content_id: '{ "library_name": "TV Shows", "episode.unwatched": true,
        "episode.inProgress": [true, false], "resume": 1, "sort": ["lastViewedAt:desc",
        "year"], "maxresults": 1 }'
    target:
      entity_id: media_player.plex_shield
  mode: single
- id: '1742764975788'
  alias: Bedroom Humidifier On
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - sensor.bedroom_climate_sensor_humidity
    below: 35
  conditions: []
  actions:
  - action: humidifier.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: humidifier.bedroom_humidifier
  mode: single
- id: '1743083579481'
  alias: Bedroom Humidifier Off
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - sensor.bedroom_climate_sensor_humidity
    for:
      hours: 0
      minutes: 20
      seconds: 0
    above: 45
  conditions: []
  actions:
  - action: humidifier.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: humidifier.bedroom_humidifier
  mode: single
- id: '1745644359091'
  alias: Toronto Maple Leafs Goal
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - sensor.toronto_maple_leafs
    attribute: team_score
  conditions:
  - condition: template
    value_template: '{{ trigger.from_state.attributes.team_score|int < trigger.to_state.attributes.team_score|int
      }}'
    enabled: true
  actions:
  - delay:
      hours: 0
      minutes: 0
      seconds: 20
      milliseconds: 0
    enabled: false
  - action: script.goal_light
    metadata: {}
    data: {}
    enabled: false
  - action: script.goal_light_leds
    metadata: {}
    data: {}
  mode: single
