
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - "/local/button-card-loader.js"
    - "/hacsfiles/kiosk-mode/kiosk-mode.js"

automation: !include automations.yaml
light: !include lights.yaml
media_player: !include media_players.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
switch: !include switches.yaml
template: !include templates.yaml

spotcast:
  sp_dc: !secret spotify_sp_dc
  sp_key: !secret spotify_sp_key
  country: CA

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/lovelace-mushroom/mushroom.js
      type: module
    - url: /hacsfiles/kiosk-mode/kiosk-mode.js
      type: module
    - url: /hacsfiles/Bubble-Card/bubble-card.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/decluttering-card/decluttering-card.js
      type: module
    - url: /hacsfiles/lovelace-hourly-weather/hourly-weather.js
      type: module
    - url: /hacsfiles/lovelace-horizon-card/lovelace-horizon-card.js
      type: module
    - url: /hacsfiles/custom-brand-icons/custom-brand-icons.js
      type: module
    - url: /hacsfiles/lovelace-flower-card/flower-card.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/android-tv-card/universal-remote-card.min.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
  dashboards:
    desktop-home:
      mode: yaml
      filename: lovelace/desktop-home.yaml
      title: Home
      icon: mdi:home
      show_in_sidebar: true
    mobile-home:
      mode: yaml
      filename: lovelace/mobile-home.yaml
      title: Home
      icon: mdi:home
      show_in_sidebar: false
