- platform: template
  switches:
    all_lights:
      value_template: >
        {{ states.light | selectattr('state','eq', 'on') | list | count > 0 }}
      turn_off:
        service: light.turn_off
        data:
          entity_id: all
      turn_on:
        service: light.turn_on
        data:
          entity_id: all

